# Generated by Django 5.2.3 on 2025-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_work',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('submitted', 'Submitted for Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=25),
        ),
    ]
