# Generated by Django 5.2.3 on 2025-06-12 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_submission_notes_assignment_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='review_comments',
            field=models.TextField(blank=True, help_text="Student's comments on the completed work", null=True),
        ),
    ]
