# Generated by Django 5.2.3 on 2025-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_rating_assignment_review_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='requirement_file_1',
            field=models.FileField(blank=True, null=True, upload_to='assignment_requirements/%Y/%m/%d/', verbose_name='Requirement File 1 (Optional)'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='requirement_file_2',
            field=models.FileField(blank=True, null=True, upload_to='assignment_requirements/%Y/%m/%d/', verbose_name='Requirement File 2 (Optional)'),
        ),
    ]
