# Generated by Django 5.2.3 on 2025-06-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_requirement_file_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submitted_work',
            field=models.FileField(null=True, upload_to='submissions/%Y/%m/%d/'),
        ),
    ]
